#
# Module 'Commvault.TypeDefinitions'
#
# Generated by: Commvault
#
# Generated on: 5/22/2019
#

Set-StrictMode -Version latest

enum CVSchedulePolicyType {
    All = -1
    DataProtection = 0
    AuxiliaryCopy = 1
    BackupCopy = 3
    OfflineContentIndexing = 6
    DDBVerification = 11
    ContentIndexing = 12
    Workflow = 13
}

enum CVBackupType {
    Full = 1
    Incremental = 2
    Differential = 3
    Synthetic_Full = 4
}

enum CVCopyPrecedence {
    Primary = 1
    Secondary = 2
    Cloud = 3
}

enum CVSQLBackupType {
    full = 1
    incremental = 2
    differential = 3
}

enum CVSQLDatabaseSortColumn {
    bkpTime
    bkpSize
    insName
    dbName
    cName
    planName
}

enum CVSQLInstanceSortColumn {
    insId
    insName
    version
    cName
    noDBs
    planName
}

enum CVVSAVMStatus {
    ALL = 0
    PROTECTED = 1
    NOT_PROTECTED = 2
    PENDING = 3
    BACKED_UP_WITH_ERROR = 4
}

enum CVVSABackupType {
    full = 1
    incremental = 2
    synthfull = 3
}

enum CVVSARestoreType {
    #GuestFiles = 1
    VirtualMachineFiles = 2
    FullVirtualMachine = 3
}

enum CVVSAHyperVisorType {
    vmware    = 101
    hyperv    = 102
    #aws       = 103
    #azure     = 104
    #openstack = 105
    #ahv       = 106
}

enum CVVSAContentOperationType {
    ADD
    DELETE
    OVERWRITE
}

<#
Object	             Numeric Value	Text Value
Server Host Name or IP Address	 1	 SERVER
Resource Pool	                 2   RES_POOL
vApp                             3   VAPP
Datacenter                       4   DATACENTER
Folder                           5   FOLDER
Cluster                          6   CLUSTER
Datastore Name                   7   DATASTORE
Datastore Cluster                8   DATASTORE_CLUSTER
Virtual Machine GUID             9   VM
Virtual Machine Name or Pattern	 10  VMName
Virtual Machine Guest OS         11  VMGuestOS
Virtual Machine Guest Host Name  12  VMGuestHostName
Cluster Shared Volumes	         13  ClusterSharedVolumes
Local Disk                       14  LocalDisk
Cluster Disk                     15  ClusterDisk
Unprotected VMs                  16  UnprotectedVMs
All	                             17  ROOT
File Server                      18  FileServer
Share                            19  SMBShare
Types                            20  TypesFolder
VMs                              21  VMFolder
Servers                          22  ServerFolder
Custom Templates                 23  TemplateFolder
Datastore List                   24  StorageRepositoryFolder
vApp List                        25  VAppFolder
Datacenters                      26  DatacenterFolder
Clusters                         27  ClusterFolder
Virtual Machine Power State      28  VMPowerState
Virtual Machine Notes            29  VMNotes
Virtual Machine Custom Attribute 30  VMCustomAttribute
Network Adapter                  31  Network
User                             32  User
Virtual Machine Template         33  VMTemplate
Tag                              34  Tag
Tag Category                     35  TagCategory
Subclient                        36  Subclient
Client Group                     37  ClientGroup
Protection Domain                38  ProtectionDomain
Consistency Group                39  ConsistencyGroup
Instance Size                    40  InstanceSize
Organization                     41  Organization
#>
enum CVVSAContentEntityType {
    SERVER	                = 1
    RES_POOL                = 2
    VAPP	                = 3
    DATACENTER	            = 4
    FOLDER	                = 5
    CLUSTER	                = 6
    DATASTORE	            = 7
    DATASTORE_CLUSTER       = 8
    VM	                    = 9
    VMName	                = 10
    VMGuestOS	            = 11
    VMGuestHostName	        = 12
    ClusterSharedVolumes    = 13
    LocalDisk               = 14
    ClusterDisk	            = 15
    UnprotectedVMs          = 16
    ROOT	                = 17
    FileServer	            = 18
    SMBShare	            = 19
    TypesFolder	            = 20
    VMFolder	            = 21
    ServerFolder            = 22
    TemplateFolder          = 23
    StorageRepositoryFolder	= 24
    VAppFolder	            = 25
    DatacenterFolder        = 26
    ClusterFolder           = 27
    VMPowerState            = 28
    VMNotes	                = 29
    VMCustomAttribute       = 30
    Network	                = 31
    User	                = 32
    VMTemplate	            = 33
    Tag	                    = 34
    TagCategory	            = 35
    Subclient	            = 36
    ClientGroup	            = 37
    ProtectionDomain        = 38
    ConsistencyGroup        = 39
    InstanceSize            = 40
    Organization            = 41
}

# Based on activityType property defined at https://documentation.commvault.com/commvault/v11/article?p=50650.htm
enum CVActivityType {
    Backup = 1
    Restore = 2
    AuxiliaryCopy = 4
    DisasterRecoveryBackup = 8
    ArchivePruning = 16
    MediaRecylce = 32
    SyntheticFull = 64
    AllActivity = 128
    Schedule = 256
    OnlineContentIndexing = 512
    OfflineContentIndexing = 1024
}
